//******************************************************************
// 
//  Generated by RoboCompDSL
//  
//  File name: Contactile.ice
//  Source: Contactile.idsl
//
//******************************************************************
#ifndef ROBOCOMPCONTACTILE_ICE
#define ROBOCOMPCONTACTILE_ICE
module RoboCompContactile
{
	struct FingerTip
	{
		float x;
		float y;
		float z;
	};
	struct FingerTips
	{
		FingerTip left;
		FingerTip right;
	};
	interface Contactile
	{
		FingerTips getValues ();
	};
};

#endif
